#!/bin/bash -eu

CPU_QUOTAS="4 3 2 1 0.75 0.5 0.25"
LOGDIR_BASE="/mnt/efs/cpu_env_tests"
DATE=$(date -u +"%Y-%m-%dT%H-%M-%SZ")

for ENV_ID in "$@"
do
    for CPU_QUOTA in $CPU_QUOTAS
    do
        logdir=$LOGDIR_BASE/$ENV_ID/$DATE/$CPU_QUOTA
        echo $logdir
        mkdir -p $logdir
        ./make-podspec.py $ENV_ID $CPU_QUOTA $logdir > $logdir/pod.yaml
        kubectl create -f $logdir/pod.yaml
    done
done
