#!/bin/bash -eu

CPU_QUOTAS="1"
LOGDIR_BASE="/mnt/efs/cpu_env_tests"
DISABLE_HYPERTHREADS=true
DATE=$(date -u +"%Y-%m-%dT%H-%M-%SZ")

for ENV_ID in "$@"
do
    for CPU_QUOTA in $CPU_QUOTAS
    do
        logdir=$LOGDIR_BASE/$ENV_ID/$DATE/$CPU_QUOTA
        echo $logdir
        mkdir -p $logdir
        ./make-podspec.py $ENV_ID $CPU_QUOTA $logdir $DISABLE_HYPERTHREADS > $logdir/pod.yaml
        kubectl create -f $logdir/pod.yaml
    done
done
